billing_profiles/urls.py
from django.urls import path

from . import views

app_name = 'billing_profiles'

urlpatterns= [
        path('nuevo', views.create, name='create'),
]

carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns =[
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
]

orders/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from . import views

app_name = 'orders'

urlpatterns = [
        path('', views.order, name='order' ),
        path('direccion', views.address, name='address'),
        path('seleccionar/direccion', views.select_address, name='select_address'),
        path('establecer/direccion/<int:pk>', views.chack_addres, name='check_address'),
        path('confirmacion', views.confirm, name='confirm'),
        path('cancelar', views.cancel, name='cancel'),
        path('completar', views.complete, name='complete'),
        path('completados', views.OrderListView.as_view(), name='completed'),
]

shipping_addresses/urls.py
from django.urls import path
from . import views

app_name = 'shipping_addresses'

urlpatterns = [ 
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('nuevo', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default'),
]

tiendaJJ/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from facilito.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/register', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('productos/', include('facilito.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('codigos/', include('promo_code.urls')),
    path('pagos/', include('billing_profiles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda JJ</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

{% include 'navbar.html' %}

    <div class="container">
        {% include 'messages.html' %}

        {% block breadcrumb %}
        
        {% endblock %}

        <div class="row mt-3">

            {% block content %}

            

            {% endblock %} 

        </div>
    </div>
</body>
<script src="https://kit.fontawesome.com/c4c520b3e6.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% block javascript %}
{% endblock %}
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
        <div class="col">
            <h4 class="text-center">{{messa}}</h4>
            {% include 'products/snippets/search.html' %}
            {% include 'products/snippets/list.html' %}
        </div>
{% endblock %}

templates/messages.html
{% if messages %}
{% for message in messages %}
    <div class="alert {% if message.tags == 'success'%}alert-success{%else%}alert-danger{%endif%} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}
{% endif %}

templates/navbar.html
{% url 'login' as login  %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %}
{% url 'shipping_addresses:shipping_addresses' as shipping_addresses %}
{% url 'orders:completed' as completed %}
{% url 'billing_profiles:create' as billing_profiles %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="{% url 'index' %}" class="navbar-brand">Tienda JJ</a>
  
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navb">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav">
        <li class="nav-item {% if request.path == cart %}active{% endif %}">
            <a class="nav-link" href="{{ cart }}">
                Mi carrito
                <span class="fas fa-shopping-cart"></span>
            </a>
        </li>
    </ul>
    <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item {% if request.path == shipping_addresses %}active{% endif %}">
            <a class="nav-link" href="{{ shipping_addresses }}">
                Mis direcciones
                <span class="fas fa-location-arrow"></span>
            </a>
        </li>
        <li class="nav-item {% if request.path == completed %}active{% endif %}">
            <a class="nav-link" href="{{ completed }}">
                Mis pedidos
                <span class="fas fa-shipping-fast"></span>
            </a>
        </li>
        <li class="nav-item {% if request.path == billing_profiles %}active{% endif %}">
            <a class="nav-link" href="{{ billing_profiles }}">
                Mis métodos de pago
                <span class="fab fa-cc-stripe"></span>
            </a>
        </li>
        {% endif %}
    </ul>
    <div class="collapse navbar-collapse justify-content-end" id="navb">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a href="{% url 'logout' %}" class="nav-link {% if request.path == logout %}active{% endif %}">
                <span class="fa-solid fa-right-from-bracket"></span>
                Logout
            </a>
        </li>
    {% else %}
        <li class="nav-item">
            <a href="{{ login }}" class="nav-link {% if request.path == login %}active{% endif %}">
                <span class="fa-solid fa-key"></span>
                Login
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ register }}" class="nav-link {% if request.path == register %}active{% endif %}">
                <span class="fa-solid fa-door-open"></span>
                Registro
            </a>
        </li>
    {% endif %}
    
    

      </ul>
    </div>
  </nav>
  